export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { bullet } = req.body;

  if (!bullet) {
    return res.status(400).json({ error: 'Bullet point is required.' });
  }

  const apiKey = process.env.GROQ_API_KEY;

  if (!apiKey) {
    return res.status(500).json({ error: 'Missing GROQ_API_KEY in environment variables.' });
  }

  try {
    const response = await fetch(
      'https://api.groq.com/openai/v1/chat/completions',
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${apiKey}`
        },
        body: JSON.stringify({
          model: 'llama-3.1-8b-instant',
          messages: [
            {
              role: 'system',
              content: 'You are an expert resume writer. Rewrite the provided resume bullet point into 3 strong, high-impact alternatives using strong action verbs and professional tone.'
            },
            {
              role: 'user',
              content: bullet
            }
          ]
        })
      }
    );

    const data = await response.json();

    if (!response.ok) {
      return res.status(response.status).json({ 
        error: data.error?.message || `Groq API Error (${response.status})` 
      });
    }

    const resultText = data.choices?.[0]?.message?.content;
    if (!resultText) {
      return res.status(500).json({ error: 'No output generated by AI model.' });
    }

    return res.status(200).json({ result: resultText });
  } catch (error) {
    return res.status(500).json({ error: error.message || 'Internal Server Error' });
  }
}
